<?php

return [
    'uyii\collections\UMap' => UP_PATH . '/collections/UMap.php',
    'uyii\collections\UMapIterator' => UP_PATH . '/collections/UMapIterator.php',
    'uyii\collections\UList' => UP_PATH . '/collections/UList.php',
    'uyii\collections\UListIterator' => UP_PATH . '/collections/UListIterator.php',
    'uyii\collections\UAttributeCollection' => UP_PATH . '/collections/UAttributeCollection.php',
    'uyii\helpers\UTextFormatter' => UP_PATH . '/helpers/UTextFormatter.php',
    'uyii\helpers\UHelper' => UP_PATH . '/helpers/UHelper.php',
    'uyii\helpers\UFile' => UP_PATH . '/helpers/UFile.php',
    'uyii\base\UFactory' => UP_PATH . '/base/UFactory.php',
    'uyii\web\UController' => UP_PATH . '/yii/web/UController.php',
    'uyii\web\UApplication' => UP_PATH . '/yii/web/UApplication.php',
    'uyii\web\UView' => UP_PATH . '/yii/web/UView.php',
    'uyii\base\UModule' => UP_PATH . '/yii/base/UModule.php',
    'uyii\base\UDummyModel' => UP_PATH . '/yii/base/UDummyModel.php',
    'uyii\base\UAction' => UP_PATH . '/yii/base/UAction.php',
    'uyii\web\auth\UAuthManager' => UP_PATH . '/yii/web/auth/UAuthManager.php',
    'uyii\web\auth\UUser' => UP_PATH . '/yii/web/auth/UUser.php',
    'uyii\web\auth\UUserIdentity' => UP_PATH . '/yii/web/auth/UUserIdentity.php',
    'uyii\worklets\UFilter' => UP_PATH . '/worklets/UFilter.php',
    'uyii\worklets\UEvent' => UP_PATH . '/worklets/UEvent.php',
    'uyii\worklets\UBehavior' => UP_PATH . '/worklets/UBehavior.php',
    'uyii\worklets\UWorklet' => UP_PATH . '/worklets/UWorklet.php',
    'uyii\worklets\UWidget' => UP_PATH . '/worklets/UWidget.php',
    'uyii\worklets\USystem' => UP_PATH . '/worklets/USystem.php',
    'uyii\worklets\UConfirm' => UP_PATH . '/worklets/UConfirm.php',
    'uyii\worklets\UMeta' => UP_PATH . '/worklets/UMeta.php',
    'uyii\worklets\UList' => UP_PATH . '/worklets/UList.php',
    'uyii\worklets\UConstructor' => UP_PATH . '/worklets/UConstructor.php',
    'uyii\worklets\UManager' => UP_PATH . '/worklets/UManager.php',
    'uyii\worklets\UForm' => UP_PATH . '/worklets/UForm.php',
    'uyii\worklets\UOrderer' => UP_PATH . '/worklets/UOrderer.php',
    'uyii\worklets\UInstall' => UP_PATH . '/worklets/UInstall.php',
    'uyii\requirements\URequirementChecker' => UP_PATH . '/yii/requirements/URequirementChecker.php',
    'uyii\i18n\UPhpMessageSource' => UP_PATH . '/yii/i18n/UPhpMessageSource.php',
];
